### ISSUE TITLE
Review before 0.1

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-partial#1]
@garyb How does this look? Can you think of anything missing?

**Comment by garyb** [comment]
Looks good to me, I think that's all there is to it.

A very minor thing in the JS - using a constant value for `{}` would probably be worthwhile, as constructing empty objects like that is surprisingly expensive.

**Comment by garyb** [comment]
I'd release as 1.0.0, by the way. For the same reason I suggested that for the prelude stuff I have in the works: we're misusing semver currently (it's supposed to go x.y.z - x is breaking, y is backwards compatible addition, z is patch/fix). I imagine this one probably isn't going to change any time soon either :wink:.

**Comment by paf31** [comment]
Sounds good, will do. The build is failing because it needs 0.8 by the way.

**Comment by garyb** [comment]
Well, not misusing exactly, as in semver `0.anything` means all bets are off and anything goes.

**Comment by garyb** [comment]
Bower.json needs fixing for pursuit publishing before 1.0 too ideally...
