### ISSUE TITLE
Isn't use of unsafeCrashWith better then using unsafePartial?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-partial#12]
I have been using unsafeCrashWith for a while now (in tests mostly) when I want to construct domain specific objects and I have to deal with Either and Maybes, but i know the input is valid. I tend to use unsafeCrashWith instead of unsafePartial because if something goes wrong I can look up the message I passed to unsafeCrashWith in source and know the location of the error.

This is what I have instead of `fromJust` and `fromRight` partial functions.

```purs
unsafeFromJust :: forall a. String -> Maybe a -> a
unsafeFromJust msg = case _ of
  Nothing -> unsafeCrashWith $ "unsafeFromJust: " <> msg
  Just a -> a

unsafeFromRight :: forall e a. Show e => String -> Either e a -> a
unsafeFromRight msg = case _ of
  Left e -> unsafeCrashWith $ "unsafeFromRight: " <> msg <> "; Left " <> show e
  Right a -> a
```

Just sharing this here might be useful for someone if others think it's a good idea might try to add to README or add unsafeFromJust and unsafeFromRight to ps-maybe ps-either.

**Comment by garyb** [comment]
Isn't this basically the same as #7?

**Comment by safareli** [comment]
Not quite the same.

**Comment by JordanMartinez** [comment]
Should we close this?

**Comment by hdgarrood** [comment]
I think we can close this in favour of https://github.com/purescript/purescript-maybe/issues/44
