### ISSUE TITLE
Document ffi function name changes

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript/purescript-partial#21]
Hey there, I'm working with the golang backend and renames like `unsafePartial` to `_unsafePartial` for FFI functions lead to runtime errors there. It would be nice to document such changes.

**Comment by garyb** [comment]
That makes sense. Perhaps it would be good to add checks in the go backend for whether the bindings are present, similar to the way it works in the JS FFI too?

**Comment by i-am-the-slime** [comment]
Definitely makes sense, I don't think it's very trivial though and requires parsing go code that *should* adhere to some conventions. @natefaubion also told me that the name changes are often because Constraints aren't allowed anymore in FFI code (that's cool!) so I see that a lot of these changes are a lot less arbitrary than I originally suspected.
